apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeportal
  namespace: kubeportal
  labels:
    app.kubernetes.io/name: kubeportal
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeportal
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeportal
    spec:
      containers:
      - name: kubeportal
        image: troeger/kubeportal:0.1.22
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: kubeportal
          mountPath: /data

      volumes:
      - name: kubeportal
        persistentVolumeClaim:
          claimName: kubeportal